import Link from "next/link";
import { MapPinIcon, PhoneIcon, MailIcon, ClockIcon, WhatsAppIcon, ArrowRightIcon } from "@/components/ui/icons";
import { formatSalonTime, getSalonSettings } from "@/lib/salon-settings";

export default async function ContactPreview() {
  const settings = await getSalonSettings();
  return <section className="border-b border-stone-200/60 bg-white py-16 md:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div className="mb-12 max-w-2xl"><div className="mb-2 inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.25em] text-[#B7925A]"><ClockIcon className="h-4 w-4"/>Visit Our Salon</div><h2 className="font-serif text-3xl font-normal tracking-tight text-[#1C1917] sm:text-4xl">Location & Opening Hours</h2><p className="mt-3 text-sm leading-relaxed text-[#78716C]">Find our salon and see when we are open. We recommend booking ahead for your visit.</p></div>
    <div className="grid gap-6 md:grid-cols-3">
      <section className="rounded-2xl border border-stone-200/80 bg-[#FAF7F2] p-7"><div className="mb-5 flex h-11 w-11 items-center justify-center rounded-xl border border-[#B7925A]/20 bg-white text-[#B7925A]"><MapPinIcon className="h-5 w-5"/></div><h3 className="font-serif text-lg font-semibold text-[#1C1917]">{settings.salonName}</h3><p className="mt-2 flex gap-2 text-sm text-stone-700"><MapPinIcon className="mt-0.5 h-4 w-4 shrink-0 text-[#B7925A]"/>{settings.address}</p><p className="mt-4 flex items-center gap-2 text-sm"><PhoneIcon className="h-4 w-4 text-[#B7925A]"/><a href={`tel:${settings.phone.replace(/[^+\d]/g, "")}`} className="hover:text-[#B7925A]">{settings.phone}</a></p><p className="mt-3 flex items-center gap-2 text-sm"><WhatsAppIcon className="h-4 w-4 text-[#B7925A]"/><a href={settings.socialMedia.whatsapp || `https://wa.me/${settings.whatsapp.replace(/\D/g, "")}`} className="hover:text-[#B7925A]">WhatsApp {settings.whatsapp}</a></p><p className="mt-3 flex items-center gap-2 text-sm"><MailIcon className="h-4 w-4 text-[#B7925A]"/><a href={`mailto:${settings.email}`} className="break-all hover:text-[#B7925A]">{settings.email}</a></p></section>
      <section className="rounded-2xl border border-stone-200/80 bg-[#FAF7F2] p-7"><div className="mb-5 flex h-11 w-11 items-center justify-center rounded-xl border border-[#B7925A]/20 bg-white text-[#B7925A]"><ClockIcon className="h-5 w-5"/></div><h3 className="font-serif text-lg font-semibold text-[#1C1917]">Opening Hours</h3><div className="mt-5 space-y-3 text-sm">{settings.openingHours.map((hour) => <div key={hour.day} className="flex justify-between gap-3 border-b border-stone-200/60 pb-2"><span className="text-stone-700">{hour.day}</span><span className="font-medium text-stone-900">{hour.isClosed ? "Closed" : `${formatSalonTime(hour.open)} – ${formatSalonTime(hour.close)}`}</span></div>)}</div></section>
      <section className="flex flex-col justify-between rounded-2xl border border-stone-200/80 bg-[#FAF7F2] p-7"><div><div className="mb-5 flex h-11 w-11 items-center justify-center rounded-xl border border-[#B7925A]/20 bg-white text-[#B7925A]"><MapPinIcon className="h-5 w-5"/></div><h3 className="font-serif text-lg font-semibold text-[#1C1917]">Plan Your Visit</h3><p className="mt-2 text-sm leading-relaxed text-[#78716C]">Get directions to {settings.address} and contact our team if you need help planning your appointment.</p></div><a href={`https://maps.google.com/?q=${encodeURIComponent(settings.address)}`} target="_blank" rel="noopener noreferrer" className="mt-6 inline-flex items-center justify-center rounded-xl border border-stone-300 bg-white py-2.5 text-sm font-medium text-stone-800 hover:border-[#B7925A] hover:text-[#B7925A]">Get Directions</a></section>
    </div>
    <div className="mt-10 flex flex-col items-center justify-between gap-4 rounded-2xl border border-stone-200/80 bg-[#FAF7F2] p-5 sm:flex-row"><p className="text-center text-sm text-[#78716C] sm:text-left">Questions about bridal packages, group bookings, or custom treatments?</p><Link href="/contact" className="inline-flex shrink-0 items-center gap-2 rounded-full bg-[#1C1917] px-6 py-2.5 text-sm font-medium text-white hover:bg-stone-800">Contact Us<ArrowRightIcon className="h-4 w-4 text-[#C5A46D]"/></Link></div>
  </div></section>;
}
